export enum ActionType {
  PRODUCT_LIST_REQUEST = 'product-list-request',
  PRODUCT_SUCCESS = 'product-success',
  PRODUCT_FAIL = 'product-fail',
  PRODUCT_DETAILS_REQUEST = 'product-details-request',
  PRODUCT_DETAILS_SUCCESS = 'product-details-success',
  PRODUCT_DETAILS_FAIL = 'product-details-fail',
  CART_ADD_ITEM = 'cart-add-item',
  CART_REMOVE_ITEM = 'cart-remove-item',
  USER_LOGIN_REQUEST = 'user-login-request',
  USER_LOGIN_SUCCESS = 'user-login-success',
  USER_LOGIN_FAIL = 'user-login-fail',
  USER_LOGOUT = 'user-logout',
  USER_REGISTER_REQUEST = 'user-register-request',
  USER_REGISTER_FAIL = 'user-register-fail',
  USER_REGISTER_SUCCESS = 'user-register-success',
  USER_DETAILS_REQUEST = 'user-details-request',
  USER_DETAILS_FAIL = 'user-details-fail',
  USER_DETAILS_SUCCESS = 'user-details-success',
  USER_DETAILS_RESET = 'user-details-reset',
}
